rm: cannot remove '355_GAS5.tmp.out': No such file or directory
Traceback (most recent call last):
  File "get_combined_score.py", line 1023, in <module>
    main()
  File "get_combined_score.py", line 699, in main
    rnn = open("%s.RNN.tab_tmp" %molname)
IOError: [Errno 2] No such file or directory: '355_GAS5.RNN.tab_tmp'

real	0m37.020s
user	0m14.308s
sys	0m5.rm: cannot remove '355_GAS5.tmp.out': No such file or directory

real	0m22.510s
user	0m13.021s
sys	0m3.677s

real	0m0.172s
user	0m0.085s
sys	0m0.073s

real	0m9.312s
user	0m9.225s
sys	0m0.040s

real	0m1.595s
user	0m1.056s
sys	0m0.528s
Read 1 item

real	38m21.768s
user	38m6.123s
sys	0m13.668s

real	0m9.190s
user	0m9.132s
sys	0m0.032s

real	0m1.847s
user	0m1.318s
sys	0m0.525s
Read 1 item

real	38m15.526s
user	37m59.190s
sys	0m14.109s

real	0m3.995s
user	0m3.930s
sys	0m0.040s

real	0m1.267s
user	0m0.790s
sys	0m0.471s
Read 1 item

real	37m53.013s
user	37m36.435s
sys	0m14.473s

real	0m15.083s
user	0m15.025s
sys	0m0.040s

real	0m1.744s
user	0m1.223s
sys	0m0.516s
Read 1 item

real	38m21.868s
user	38m5.291s
sys	0m14.283s

real	0m3.161s
user	0m3.099s
sys	0m0.032s

real	0m0.930s
user	0m0.393s
sys	0m0.530s
Read 1 item

real	39m11.014s
user	38m53.627s
sys	0m14.506s

real	0m26.900s
user	0m26.853s
sys	0m0.032s

real	0m1.355s
user	0m0.871s
sys	0m0.479s
Read 1 item

real	32m15.383s
user	32m0.788s
sys	0m11.278s

real	0m22.063s
user	0m21.995s
sys	0m0.036s

real	0m2.007s
user	0m1.425s
sys	0m0.515s
Read 1 item

real	39m21.402s
user	39m3.260s
sys	0m14.460s

real	0m9.367s
user	0m9.285s
sys	0m0.032s

real	0m1.468s
user	0m0.984s
sys	0m0.476s
Read 1 item

real	38m42.657s
user	38m19.351s
sys	0m14.831s
f, **self.options)
  File "/apps/PYTHON/2.7.14/INTEL/lib/python2.7/site-packages/pandas/io/parsers.py", line 1853, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 387, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 705, in pandas._libs.parsers.TextReader._setup_parser_source
IOError: [Errno 2] File 355_GAS5.RNN_NP_ONLY.csv does not exist: '355_GAS5.RNN_NP_ONLY.csv'

real	0m0.060s
user	0m0.025s
sys	0m0.029s
split: cannot open '355_GAS5.SHAPE' for reading: No such file or directory
ls: cannot access '/gpfs/projects/bsc40/uchorostecki/projects/MULTI-FOLDS/multiple_conformations/23_degrees/355_GAS5_23_180_60/res/splited_*': No such file or directory
mv: cannot stat '/gpfs/projects/bsc40/uchorostecki/projects/MULTI-FOLDS/multiple_conformations/23_degrees/355_GAS5_23_180_60/res/*_*.SHAPE': No such file or directory
ls: cannot access '/gpfs/projects/bsc40/uchorostecki/projects/MULTI-FOLDS/multiple_conformations/23_degrees/355_GAS5_23_180_60/final/*SHAPE': No such file or directory
ls: cannot access '/gpfs/projects/bsc40/uchorostecki/projects/MULTI-FOLDS/multiple_conformations/23_degrees/355_GAS5_23_180_60/final/*.ct': No such file or directory
